name: Deploy Python Flask App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if APP_NAME secret exists
      - name: Verify required secrets exist
        run: |
          if [ -z "${{ secrets.APP_MESSAGE }}" ] || [ -z "${{ secrets.APP_HEALTH }}" ]; then
            echo "Required secrets (APP_MESSAGE, APP_HEALTH) are not set."
            echo "Add them under: Settings → Secrets and variables → Actions"
            exit 1
            else
            echo "APP_MESSAGE and  APP_HEALTH secret exist."
          fi

      # Create .env file from secret
      - name: Create .env file from secrets
        run: |
          echo "APP_MESSAGE=${{ secrets.APP_MESSAGE }}" > .env
          echo "APP_HEALTH=${{ secrets.APP_HEALTH }}" >> .env
          echo "---- .env created from secrets ----"

      # (Optional) view .env file contents (for debug, without secrets)
      - name: Confirm .env file created
        run: cat .env | sed 's/=.*/=<hidden>/'

      # Build and run Docker container
      - name: Build and run Docker container
        run: docker compose up --build -d
